force-app/main/default/objects/MA_Shipment__c/MA_Shipment__c.object-meta.xml
<CustomObject>
    <label>MA: Shipment</label>
    <nameField>
        <displayFormat>MA-{0000000000}</displayFormat>
        <label>MA: Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MA: Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MA_Shipment__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Tracking Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/MA_ShipmentStatusBatchable.cls
global class MA_ShipmentStatusBatchable implements Database.Batchable<sObject>, Schedulable {
    // Database.Stateful, Database.AllowsCallouts,
    // global MA_ShipmentStatusBatchable() {}

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id, Tracking_Number__c, Status__c FROM MA_Shipment__c WITH SECURITY_ENFORCED]);
        // best to keep SOQL query with filtration criteria in the start method]
        // e.g. ... WHERE Status__c = 'Pending' ...
    }

    global void execute(Database.BatchableContext BC, List<MA_Shipment__c> scope) {
        MA_ShipmentService.upudateStatuses(scope);
    }

    // Finish method: Perform post-processing or cleanup
    global void finish(Database.BatchableContext BC) {
        // Perform any post-processing or cleanup if needed.
    }

    // Schedulable Interface Method: Define how to schedule the batch job
    global void execute(SchedulableContext SC) {
        MA_ShipmentStatusBatchable batchJob = new MA_ShipmentStatusBatchable();
        Database.executeBatch(batchJob);
    }
}